### ISSUE TITLE
Notebook task job spec

### ISSUE THREAD

**Issue by bweisberg** [databrickslabs/cicd-templates#18]
I need to write pipeline tests as Scala Notebooks.  Will the databrickslabs_cicdtemplates Python module support more job specs? 

for example:
```
  "notebook_task": {
    "notebook_path": "will get filled automatically"
  }
```

**Comment by chinwobble** [comment]
@renardeinside I've looked through all the source code for dbx and I can't find any reference that supports executing or deploying notebook job tasks. 

Could you elaborate on how to get this working?

**Comment by renardeinside** [comment]
Hi @chinwobble . 

Notebook-based development is not a part of `dbx` (at least for now), so the **execute** functionality won't work. Also, we don't support (at least for now) the local-to-workspace notebook sync. 

For the deployment part, specify the notebook spec in the `deployment.json` file. 
An example is here:
```js
"jobs": [
 {
     "name": "my-notebook-job",
     
     // here goes your cluster spec etc
     
     "notebook_task": {
         "notebook_path": "/Users/my-username@example.com/workspace/path/to/notebook/notebook-name"
     }
 }
]
```
Here we use the REST API 2.0. Please find additional params for the `notebook_task` section [here](https://docs.databricks.com/dev-tools/api/latest/jobs.html#notebooktask).
