### ISSUE TITLE
Problem running dbx execute with example

### ISSUE THREAD

**Issue by dexianta** [databrickslabs/cicd-templates#28]
I'm not able to run `dbx execute --cluster-name my-cluster --job job-sample`. As far as I understand, in `dbx execute`, wheel was built, copied to dbfs, and `jobs/sample/entrypoint.py` was serialized to directly run on the interactive cluster, without providing `--conf-file`. However the `Job` class defined in  `project_name/common.py` requires `--conf-file`, thus exception were thrown
![image](https://user-images.githubusercontent.com/58335017/97049538-296bf100-157c-11eb-93fc-a02814fa1f0b.png)

========================================
So far, it seems to me that:
- dbx execute is suitable to launch script without external config files, since it's using 1.2 API command execute.
- if I want to run the local code on interactive cluster (for fast dev iteration), I'll need a separate job json with "exisiting_cluster_id". then run launch (which is /job/run-now underneath)

**Comment by renardeinside** [comment]
> dbx execute is suitable to launch script without external config files, since it's using 1.2 API command execute.
Yes, you're correct in this understanding.

>if I want to run the local code on interactive cluster (for fast dev iteration), I'll need a separate job json with "exisiting_cluster_id". then run launch (which is /job/run-now underneath)

I'll provide the functionality to add a `default_conf ` method, which allows you to provide a default configuration for `dbx execute` launch.

**Comment by renardeinside** [comment]
@dexianta please check the latest version and especially the `init_adapter` method.

**Comment by dexianta** [comment]
> @dexianta please check the latest version and especially the `init_adapter` method.

@renardeinside thank you very much
