### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptography.hazmat.backends'

### ISSUE THREAD

**Issue by WightmanVH** [databrickslabs/cicd-templates#35]
Following the instructions in the readme results in an error (before adding any additional code). Run 'dbx -- version' before adding any actual application code.
Environment: Windows 10 with Anaconda.  Same error for AWS and Azure cookiecutter

**Comment by renardeinside** [comment]
Hi @WightmanVH , were you able to resolve this issue? We don't have a `cryptography` module in 1.0.0/1.0.1/1.0.2 releases.

**Comment by WightmanVH** [comment]
Yes, I went back and looked a little more closely at the results of the 'pip install -U tools/dbx-0.7.0-py3-none-any.whl' command. What I saw was this:

`
Requirement already satisfied, skipping upgrade: cryptography>=2.1.4 in c:\program files\amazon\awscliv2 (from azure-storage-blob>=12.0->mlflow>=1.11.0->dbx==0.7.0) (2.8)
WARNING: No metadata found in c:\program files\amazon\awscliv2
`
I just uninstalled the awscliv2 and re-ran the command, and it worked.  

`Installing collected packages: dbx, cryptography
  Attempting uninstall: dbx
    Found existing installation: dbx 0.7.0
    Uninstalling dbx-0.7.0:
      Successfully uninstalled dbx-0.7.0
Successfully installed cryptography-3.2 dbx-0.7.0
`
