### ISSUE TITLE
Windows issue with replacing workspace_dir file forward slash with backward slashes

### ISSUE THREAD

**Issue by WightmanVH** [databrickslabs/cicd-templates#37]
Running on Windows, the project.json values (+ local file locations?) seem to cause an error.  Python seems to be trying to replace forward slashes with backward slashes
[windows_file_error.txt](https://github.com/databrickslabs/cicd-templates/files/5448379/windows_file_error.txt)

The documentation notes that the dbx commands are executed in bash.  Is Windows not supported?

(dbconnect_aws) C:\Users\user1\sample_aws>dbx execute --cluster-name=test-cluster --job=sample_aws-sample-integration-test
Traceback (most recent call last):
  File "c:\local\miniconda3\envs\dbconnect_aws\lib\site-packages\databricks_cli\sdk\api_client.py", line 131, in perform_query
    resp.raise_for_status()
  File "c:\local\miniconda3\envs\dbconnect_aws\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://x.databricks.com/api/2.0/workspace/mkdirs

...

 Response from server:
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': "Path (\\Shared\\dbx\\projects) doesn't start with '/'"}

**Comment by renardeinside** [comment]
Hi @WightmanVH , Windows should be supported, however we lack of platform-specific tests. I'll address this issue in the mentioned PR.

**Comment by renardeinside** [comment]
Hi @WightmanVH , please check out the latest version (1.0.3), I've fixed the problem with paths on Win-based platforms and added tests for this type of environment.

**Comment by WightmanVH** [comment]
Hi @renardeinside , I was able to test the latest version.  It worked great in my Windows environment 👍
