### ISSUE TITLE
Generated README sample using wrong dbx command

### ISSUE THREAD

**Issue by steve148** [databrickslabs/cicd-templates#39]
Was playing with the project today and I noticed a small issue in the docs that get generated after creating the project via cookiecutter. Specifically the snippet in the README can be found at https://github.com/databrickslabs/cicd-templates/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#testing for the following snippet.

----
For a test on a automated job cluster, use `launch` instead of `execute`:
```
dbx execute --job=cicd-sample-project-sample-integration-test
```
----

Based on my understanding of the project and its commands, I think the snippet should be the following

```
dbx launch --job=cicd-sample-project-sample-integration-test
```

If you guys are taking Pull Requests, I'll fork and put the fix up for review to help out. I've been enjoying go through this project, so kudos to you.

**Comment by renardeinside** [comment]
Hi @steve148 , yes, you're right, here should be `dbx launch`. Feel free to fire a PR :)

**Comment by renardeinside** [comment]
Hi @steve148 , thanks a lot for your help!
