### ISSUE TITLE
IndexError: string index out of range when deploying artifact

### ISSUE THREAD

**Issue by ThunderShiviah** [databrickslabs/cicd-templates#4]
<img width="1334" alt="Screen Shot 2020-05-17 at 14 15 49" src="https://user-images.githubusercontent.com/7097428/82147939-19234d80-9849-11ea-9603-37a92b220130.png">

**Comment by mshtelma** [comment]
Is it possible that DATABRICKS_HOST was not set or was set to a wrong value? The error occurs in databricks_cli. 
I think I will have to add some checks for the host value
