### ISSUE TITLE
Error when using dbutils.secrets in Integration tests

### ISSUE THREAD

**Issue by kiranvasudev** [databrickslabs/cicd-templates#42]
Hello,
   I would like to write integration tests that need to use one/many Databricks secrets. Unfortunately, for the tests that use `dbutils.secrets.get()`, the following error message is thrown:

![image](https://user-images.githubusercontent.com/16002904/98798381-1f684000-240e-11eb-8006-8ed7b4cdd0f7.png)

This happens when I execute the test when using `dbx` directly from the command line, as well as when I deploy it as a job on Databricks and launch it from there.

Is there a way that secrets can be accessed when running the tests?

**Comment by renardeinside** [comment]
Hi @kiranvasudev ! I'll check for options and let you know. I have two ideas, let me check which of them is better :)

**Comment by renardeinside** [comment]
Hi @kiranvasudev . I can not reproduce this issue in my testing environment, for me the `dbutils.secrets.get` are working pretty fine. Do you still have this issue?

**Comment by renardeinside** [comment]
Please reopen the issue if the problem preserves.
