### ISSUE TITLE
Create and manage persistent clusters 

### ISSUE THREAD

**Issue by Laudenlaruto** [databrickslabs/cicd-templates#47]
Hello,

I was wondering if it was possible to define persistent cluster within the deployment.json file. Side by side with the jobs definition.
With something like the following syntax:
```
{
    "default": {
        "clusters": [{
            "cluster_name": "test",
            ...   
            }
        }],
        "jobs": [{
            "name": "test",
            "existing_cluster_id": "test",
            ....
        }]
    }
}
```

**Comment by renardeinside** [comment]
Hi @Laudenlaruto !
This functionality is already provided by [databricks-cli](https://docs.databricks.com/dev-tools/cli/index.html). 
In `dbx` we concentrate on CI and deployment, but the creation of a persistent cluster is more about infrastructure settings.
Please use databricks CLI to create a persistent cluster, and then provide the cluster id into `deployment.json`.

**Comment by Laudenlaruto** [comment]
Ok thank you very much for the clarification.
