### ISSUE TITLE
If user provides directory for mlflow experiment on set up, create an experiment with a default name instead of throwing error.

### ISSUE THREAD

**Issue by ThunderShiviah** [databrickslabs/cicd-templates#5]
Exception: INVALID_PARAMETER_VALUE: Expected id '3624504707471432' to be an MLflow experiment or Databricks notebook, found 'DIRECTORY'. If this experiment id was previously valid, your experiments may have been migrated. For more information, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.".

**Comment by renardeinside** [comment]
This is fixed with the latest update.
