### ISSUE TITLE
dbx execute doesn't work on ml cluster

### ISSUE THREAD

**Issue by chinwobble** [databrickslabs/cicd-templates#51]
If you attempt to run dbx execute it won't work on ml clusters.

Since 
```
%pip install -U -r {path}
```

Is only supported on databricks runtime and not databricks ML Cluster

**Comment by renardeinside** [comment]
Hi @chinwobble ! 

I'm not sure if I understand your issue properly. 
`%pip` is supported as per [this](https://docs.databricks.com/libraries/notebooks-python-libraries.html) documentation.
In the quickstart example, we use 7.3 ML LTS.
Could you please specify the version where it is not working?

**Comment by chinwobble** [comment]
I tested it on a ML Cluster 6.4 LTS and it wasn't working. 
My mistake, happy to close this issue.
